###
GET http://localhost:1337/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJyb2xlIjoyLCJpYXQiOjE3Mzk4NzY1NTh9.kxUwSuR7iRQRYWoZJrYcKhgyuyh7LpmOOk-ApogAqpo

###
POST http://localhost:1337/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@gmail.com",
    "contact": "123456789",
    "password": "password"
}

### invalid email login
POST http://localhost:1337/login
Content-Type: application/json

{
    "email": "johndoe@gmail",
    "password": "password"
}

### invalid password login
POST http://localhost:1337/login
Content-Type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "wrongPassword"
}

### valid login
POST http://localhost:1337/login
Content-Type: application/json

{
    "email": "iankim10834@gmail.com",
    "password": "Password@1"
}

### register user
POST http://localhost:1337/register
Content-Type: application/json

{
     "name" : "Ian",
     "email" : "kiwitichani0@gmail.com",
     "contact" : "129345678",
     "password": "Hello@67"
 }

### Get products route
GET https://localhost:1337/price-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMiwicm9sZSI6MiwiaWF0IjoxNzQzMjY5OTM0LCJleHAiOjE3NDMyNzM1MzR9.K2EsmnDowPP1YNoEnp-v4WE8QmXGmzD9rakYempJZxk